name: Demo pipeline

on:
  workflow_dispatch:

jobs:
  plan:
    runs-on:
      group: org/ubuntu-runners
    steps:
      - name: Running plan
        run: echo "Running plan"

  apply:
    runs-on:
      group: org/ubuntu-runners
    environment: "Restricted"
    steps:
      - name: Running apply
        run: echo "Running apply"
