name: Demo pipeline

on:
  push:

jobs:
  test:
    runs-on:
      group: org/ubuntu-runners
    steps:

      - name: Start EC2 runner
        id: start-ec2-runner
        uses: machulav/ec2-github-runner@v2
        with:
          mode: start
          github-token: "x" #
          ec2-image-id: "x" #
          ec2-instance-type: t2.micro
          subnet-id: 	"x" #
          security-group-id: "x" #${{ env.PE_SG }}
